Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,10 @@
 name: Build by  fireworld & Test
 on:
   workflow_dispatch:
+env:
+  # Our build metadat
+  TAG_NAME: "nightly"
+  VERSION: "2.0.0"
 jobs:
   Test:
     runs-on: ubuntu-latest
@@ -8,6 +12,33 @@ jobs:
     steps:
     - name: Check out source code
       uses: actions/checkout@v4
+    - name: Get tag version
+      run: |
+          # 如果是手动触发 (workflow_dispatch)
+          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
+            # 获取所有 Tag（确保包含远程 Tag）
+            git fetch --tags
+            # 按版本号排序获取最新 Tag（兼容语义化版本）
+            LATEST_TAG=$(git tag --sort=-v:refname | head -n 1 || echo "nightly")
+
+            # 去掉 Tag 名称中的 'v' 前缀
+            VERSION=$(grep versionName uhabits-android/build.gradle.kts | sed -e 's/.*"\([^"]*\)".*/\1/g')
+          else
+           # 原有逻辑：从推送的 Tag 中提取版本号
+           TAG_VERSION="${GITHUB_REF##*/}"
+           VERSION="${TAG_VERSION}"
+          fi
+
+          # 处理无 Tag 的情况（可选：报错或默认值）
+          if [ -z "$VERSION" ]; then
+            echo "::error::No valid tag found!"
+            VERSION="0.0.0"
+          fi
+
+          # 将信息写入环境变量
+          echo "TAG_NAME=$LATEST_TAG" >> $GITHUB_ENV
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+      
 
     - name: Build project
       env:
@@ -20,9 +51,9 @@ jobs:
         VERSION=$(grep versionName uhabits-android/build.gradle.kts | sed -e 's/.*"\([^"]*\)".*/\1/g')
         echo ${{ secrets.LOOP_SIGNKEY }} | base64 --decode > ${{ github.workspace }}/key.jks
         ./gradlew uhabits-android:assembleRelease
-        cp -v \
+        mv  \
             uhabits-android/build/outputs/apk/release/uhabits-android-release.apk \
-            uhabits-android/build/loop-"$VERSION"-release.apk
+            uhabits-android/build/outputs/apk/release/loop-"$VERSION"-release.apk
 
     - name: Upload artifacts
       if: always()
@@ -30,4 +61,12 @@ jobs:
       with:
         name: build
         path: |
-          uhabits-android/build
+          uhabits-android/build/outputs/apk/release/
+          
+    - name: Publish signed apk package
+      uses: softprops/action-gh-release@v2
+      with:
+          prerelease: false
+          tag_name: ${{ env.TAG_NAME }}
+          files: |
+            uhabits-android/build/outputs/apk/release/
